workflows:
  android-build:
    name: Build Android APK
    max_build_duration: 20
    environment:
      flutter: stable
    scripts:
      - name: Get dependencies
        script: flutter pub get
      - name: Build release APK (Android only)
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk

    # ✨ Add this to skip iOS completely
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
          include: true
      cancel_previous_builds: true
