name: qr_inventory
description: QR Inventory App for warehouse check
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  mobile_scanner: ^3.3.0

flutter:
  uses-material-design: true